version: '3.8'

services:
  minio:
    image: quay.io/minio/minio
    container_name: meu-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: aws_certified
      MINIO_ROOT_PASSWORD: super_senha_123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  airflow:
    image: apache/airflow:2.7.1-python3.10
    container_name: meu-airflow
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "8080:8080"
    command: bash -c "pip install -r /opt/airflow/scripts/requirements.txt && airflow db init && airflow users create --username admin --firstname Kaua --lastname Admin --role Admin --email admin@example.com --password admin && (airflow webserver & exec airflow scheduler)"
    volumes:
      # Mapeia a pasta dags para o Airflow ler o pipeline
      - ./dags:/opt/airflow/dags
      # Mapeia a sua pasta atual para o Airflow conseguir executar os seus scripts Python
      - .:/opt/airflow/scripts
    user: "${AIRFLOW_UID:-50000}:0"

  # 🌟 MOVIDOS PARA CÁ: Agora eles estão corretamente sob o bloco "services"
  # --- BANCO DE DADOS (Data Warehouse para a Camada Gold) ---
  postgres_dw:
    image: postgres:15
    container_name: postgres_dw
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: gold_db
    ports:
      - "5433:5432" # Usando a porta 5433 no seu PC para evitar conflito com o Postgres do Airflow

  # --- FERRAMENTA DE BI E DASHBOARDS ---
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3000:3000"
    depends_on:
      - postgres_dw

# 📦 O bloco volumes agora contém apenas os discos virtuais declarados
volumes:
  minio_data: