version: '3.8'

services:
  minio:
    image: quay.io/minio/minio
    container_name: meu-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: aws_certified
      MINIO_ROOT_PASSWORD: super_senha_123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  minio_data: